<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_DcZ0Yd5uEeqbhffMpNXt5w" name="MiDiagrama" author="usuario" bonitaVersion="6.2.4" bonitaModelVersion="6.2.4-001" configId="ACED00057400184D694469616772616D61362E322E342D303031362E322E34">
    <elements xmi:type="process:Pool" xmi:id="_Dpo_IN5uEeqbhffMpNXt5w" name="Proceso de Emprendimientos" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xmi:type="process:Lane" xmi:id="_DwTn0N5uEeqbhffMpNXt5w" name="Emprendedor" actor="_DwM6IN5uEeqbhffMpNXt5w">
        <elements xmi:type="process:Task" xmi:id="_DxHgIN5uEeqbhffMpNXt5w" name="Reclutamiento de emprendedores" outgoing="_aj-skN5xEeqK1fIfy8doog" incoming="_D25_EN5uEeqbhffMpNXt5w _krUI8N5xEeqK1fIfy8doog" actor="_1MUVwN50EeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_DxJVUt5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DxJVUN5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DxIuQN5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DxJVUd5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_DxJ8YN5uEeqbhffMpNXt5w">
            <cardinality xmi:type="expression:Expression" xmi:id="_DxJ8Yd5uEeqbhffMpNXt5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_DxJ8Yt5uEeqbhffMpNXt5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_DxJVU95uEeqbhffMpNXt5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_DxJVVN5uEeqbhffMpNXt5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_h8H6oN54EeqK1fIfy8doog" name="ReclutamientoDeEmprendedores" nColumn="2" nLine="8">
            <widgets xmi:type="form:TextFormField" xmi:id="_h8H6od54EeqK1fIfy8doog" name="convocatoria1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_h8H6ot54EeqK1fIfy8doog"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_h8H6o954EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_h8H6pN54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_h8H6pd54EeqK1fIfy8doog" name="convocatoria" content="convocatoria" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_h8H6pt54EeqK1fIfy8doog" name="convocatoria" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_h8H6p954EeqK1fIfy8doog" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_h8H6qN54EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_h8H6qd54EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_h8H6qt54EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_h8H6q954EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_h8H6rN54EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_h8H6rd54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_h8H6rt54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_h8H6r954EeqK1fIfy8doog" name="Convocatoria" content="Convocatoria" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_h8H6sN54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8H6sd54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8H6st54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_h8H6s954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_h8H6tN54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_h8H6td54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_h8H6tt54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_h8H6t954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:TextFormField" xmi:id="_h8H6uN54EeqK1fIfy8doog" name="descripcion_de_emprendimiento1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_h8H6ud54EeqK1fIfy8doog" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_h8H6ut54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_h8H6u954EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_h8H6vN54EeqK1fIfy8doog" name="descripcion_de_emprendimiento" content="descripcion_de_emprendimiento" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_h8H6vd54EeqK1fIfy8doog" name="descripcion_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_h8H6vt54EeqK1fIfy8doog" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_h8H6v954EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_h8H6wN54EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_h8H6wd54EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_h8H6wt54EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_h8H6w954EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_h8H6xN54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_h8H6xd54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_h8H6xt54EeqK1fIfy8doog" name="Descripcion del emprendimiento" content="Descripcion del emprendimiento" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_h8H6x954EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8H6yN54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8H6yd54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_h8H6yt54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_h8H6y954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_h8H6zN54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_h8H6zd54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_h8H6zt54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:TextFormField" xmi:id="_h8H6z954EeqK1fIfy8doog" name="necesidad_del_mercado1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_h8H60N54EeqK1fIfy8doog" line="2" column="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_h8H60d54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_h8H60t54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_h8H60954EeqK1fIfy8doog" name="necesidad_del_mercado" content="necesidad_del_mercado" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_h8H61N54EeqK1fIfy8doog" name="necesidad_del_mercado" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_h8H61d54EeqK1fIfy8doog" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_h8H61t54EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_h8H61954EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_h8H62N54EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_h8H62d54EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_h8H62t54EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_h8H62954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_h8H63N54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_h8H63d54EeqK1fIfy8doog" name="Necesidad del mercado" content="Necesidad del mercado" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_h8H63t54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8H63954EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8H64N54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_h8H64d54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_h8H64t54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_h8H64954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_h8H65N54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_h8H65d54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:TextFormField" xmi:id="_h8H65t54EeqK1fIfy8doog" name="resumen_de_emprendimiento1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_h8H65954EeqK1fIfy8doog" line="1" column="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_h8H66N54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_h8H66d54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_h8H66t54EeqK1fIfy8doog" name="resumen_de_emprendimiento" content="resumen_de_emprendimiento" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_h8H66954EeqK1fIfy8doog" name="resumen_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_h8H67N54EeqK1fIfy8doog" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_h8H67d54EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_h8H67t54EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_h8H67954EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_h8H68N54EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_h8H68d54EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_h8H68t54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_h8H68954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_h8IhsN54EeqK1fIfy8doog" name="Resumen de emprendimiento" content="Resumen de emprendimiento" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_h8Ihsd54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8Ihst54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8Ihs954EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_h8IhtN54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_h8Ihtd54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_h8Ihtt54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_h8Iht954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_h8IhuN54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:TextFormField" xmi:id="_h8Ihud54EeqK1fIfy8doog" name="tipo_de_emprendimiento1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_h8Ihut54EeqK1fIfy8doog" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_h8Ihu954EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_h8IhvN54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_h8Ihvd54EeqK1fIfy8doog" name="tipo_de_emprendimiento" content="tipo_de_emprendimiento" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_h8Ihvt54EeqK1fIfy8doog" name="tipo_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_h8Ihv954EeqK1fIfy8doog" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_h8IhwN54EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_h8Ihwd54EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_h8Ihwt54EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_h8Ihw954EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_h8IhxN54EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_h8Ihxd54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_h8Ihxt54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_h8Ihx954EeqK1fIfy8doog" name="Tipo de emprendimiento" content="Tipo de emprendimiento" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_h8IhyN54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8Ihyd54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8Ihyt54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_h8Ihy954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_h8IhzN54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_h8Ihzd54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_h8Ihzt54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_h8Ihz954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:TextFormField" xmi:id="_h8Ih0N54EeqK1fIfy8doog" name="titulo_de_emprendimiento1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_h8Ih0d54EeqK1fIfy8doog" column="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_h8Ih0t54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_h8Ih0954EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_h8Ih1N54EeqK1fIfy8doog" name="titulo_de_emprendimiento" content="titulo_de_emprendimiento" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_h8Ih1d54EeqK1fIfy8doog" name="titulo_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_h8Ih1t54EeqK1fIfy8doog" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_h8Ih1954EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_h8Ih2N54EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_h8Ih2d54EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_h8Ih2t54EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_h8Ih2954EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_h8Ih3N54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_h8Ih3d54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_h8Ih3t54EeqK1fIfy8doog" name="Titulo de emprendimiento" content="Titulo de emprendimiento" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_h8Ih3954EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8Ih4N54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8Ih4d54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_h8Ih4t54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_h8Ih4954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_h8Ih5N54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_h8Ih5d54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_h8Ih5t54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:TextFormField" xmi:id="_h8Ih5954EeqK1fIfy8doog" name="ubicacion_de_emprendimiento1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_h8Ih6N54EeqK1fIfy8doog" line="3"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_h8Ih6d54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_h8Ih6t54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_h8Ih6954EeqK1fIfy8doog" name="ubicacion_de_emprendimiento" content="ubicacion_de_emprendimiento" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_h8Ih7N54EeqK1fIfy8doog" name="ubicacion_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_h8Ih7d54EeqK1fIfy8doog" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_h8Ih7t54EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_h8Ih7954EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_h8Ih8N54EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_h8Ih8d54EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_h8Ih8t54EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_h8Ih8954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_h8Ih9N54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_h8Ih9d54EeqK1fIfy8doog" name="Ubicación de emprendimiento" content="Ubicación de emprendimiento" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_h8Ih9t54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8Ih9954EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_h8Ih-N54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_h8Ih-d54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_h8Ih-t54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_h8Ih-954EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_h8Ih_N54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_h8Ih_d54EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_h8Ih_t54EeqK1fIfy8doog" name="Enviar1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_h8Ih_954EeqK1fIfy8doog" line="4"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_h8IiAN54EeqK1fIfy8doog" name="Enviar" content="Enviar" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_h8IiAd54EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_h8IiAt54EeqK1fIfy8doog" name="Reclutamiento de emprendedores" content="Reclutamiento de emprendedores" returnTypeFixed="true"/>
          </form>
          <transientData xmi:type="process:Data" xmi:id="_DBWrkN54EeqK1fIfy8doog" name="convocatoria" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_DBWrkd54EeqK1fIfy8doog" content=""/>
          </transientData>
          <transientData xmi:type="process:Data" xmi:id="_EU_dsN54EeqK1fIfy8doog" name="titulo_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_EU_dsd54EeqK1fIfy8doog" content=""/>
          </transientData>
          <transientData xmi:type="process:Data" xmi:id="_HutLgN54EeqK1fIfy8doog" name="ubicacion_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_HutLgd54EeqK1fIfy8doog" content=""/>
          </transientData>
          <transientData xmi:type="process:Data" xmi:id="_cnv28N54EeqK1fIfy8doog" name="tipo_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_cnv28d54EeqK1fIfy8doog" content=""/>
          </transientData>
          <transientData xmi:type="process:Data" xmi:id="_eNXw8N54EeqK1fIfy8doog" name="resumen_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_eNXw8d54EeqK1fIfy8doog" content=""/>
          </transientData>
          <transientData xmi:type="process:Data" xmi:id="_fm3TcN54EeqK1fIfy8doog" name="descripcion_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_fm3Tcd54EeqK1fIfy8doog" content=""/>
          </transientData>
          <transientData xmi:type="process:Data" xmi:id="_g36roN54EeqK1fIfy8doog" name="necesidad_del_mercado" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_g36rod54EeqK1fIfy8doog" content=""/>
          </transientData>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_DxJVVd5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_DxJVVt5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_D1Y8IN5uEeqbhffMpNXt5w" name="Inicio" outgoing="_D25_EN5uEeqbhffMpNXt5w">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_D1iGE95uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D1iGEd5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D1iGEN5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D1iGEt5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_N_Sc8N5xEeqK1fIfy8doog" name="¿quiere ser emprendedor?" outgoing="_hHTPoN5xEeqK1fIfy8doog _1F1IsN5zEeqK1fIfy8doog" incoming="_aj-skN5xEeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_N_TEA95xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_N_TEAd5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_N_TEAN5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_N_TEAt5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_DeafMd5xEeqK1fIfy8doog" name="Sensibilización">
        <elements xmi:type="process:ANDGateway" xmi:id="_hHNwEN5xEeqK1fIfy8doog" name="¿se va a sensibilizar?" outgoing="_krUI8N5xEeqK1fIfy8doog _sFI2MN5xEeqK1fIfy8doog" incoming="_hHTPoN5xEeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_hHOXI95xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hHOXId5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hHOXIN5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hHOXIt5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_u85GcN5xEeqK1fIfy8doog" name="¿tiene emprendimiento?" outgoing="_xMcHMN5xEeqK1fIfy8doog _6r6SUN5xEeqK1fIfy8doog" incoming="_u8-mAN5xEeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_u85tg95xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_u85tgd5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_u85tgN5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_u85tgt5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Y9kBAN50EeqK1fIfy8doog" name="Eventos" outgoing="_u8-mAN5xEeqK1fIfy8doog" incoming="_sFI2MN5xEeqK1fIfy8doog _xMcHMN5xEeqK1fIfy8doog _tFylcN5yEeqK1fIfy8doog _D90QoN50EeqK1fIfy8doog" actor="_3RTFQN50EeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_sEXaJN5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sEXaIt5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sEXaId5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sEXaI95xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_sEYBMN5xEeqK1fIfy8doog">
            <cardinality xmi:type="expression:Expression" xmi:id="_sEYBMd5xEeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_sEYBMt5xEeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_sEXaJd5xEeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_sEXaJt5xEeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_A9AjUN56EeqK1fIfy8doog" name="Eventos">
            <widgets xmi:type="form:TextFormField" xmi:id="_A9AjUd56EeqK1fIfy8doog" name="descripcion1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_A9AjUt56EeqK1fIfy8doog"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_A9AjU956EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_A9AjVN56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_A9AjVd56EeqK1fIfy8doog" name="descripcion" content="descripcion" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_A9AjVt56EeqK1fIfy8doog" name="descripcion" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_A9AjV956EeqK1fIfy8doog" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_A9AjWN56EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_A9AjWd56EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_A9AjWt56EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_A9AjW956EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_A9AjXN56EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_A9AjXd56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_A9AjXt56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_A9AjX956EeqK1fIfy8doog" name="Descripcion" content="Descripcion" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_A9AjYN56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_A9AjYd56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_A9AjYt56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_A9AjY956EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_A9AjZN56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_A9AjZd56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_A9AjZt56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_A9AjZ956EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:DateFormField" xmi:id="_A9AjaN56EeqK1fIfy8doog" name="fecha1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_A9Ajad56EeqK1fIfy8doog" line="1"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_A9Ajat56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_A9Aja956EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_A9AjbN56EeqK1fIfy8doog" name="fecha" content="fecha" type="TYPE_VARIABLE" returnType="java.util.Date">
                <referencedElements xmi:type="process:Data" xmi:id="_A9Ajbd56EeqK1fIfy8doog" name="fecha" dataType="_DcZ0Y95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_A9Ajbt56EeqK1fIfy8doog" content="" returnType="java.util.Date"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_A9Ajb956EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_A9AjcN56EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_A9Ajcd56EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_A9Ajct56EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_A9Ajc956EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_A9AjdN56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_A9Ajdd56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_A9Ajdt56EeqK1fIfy8doog" name="Fecha" content="Fecha" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_A9Ajd956EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_A9AjeN56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_A9Ajed56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_A9Ajet56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_A9Aje956EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_A9AjfN56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_A9Ajfd56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_A9Ajft56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:TextFormField" xmi:id="_A9Ajf956EeqK1fIfy8doog" name="nombre_evento1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_A9AjgN56EeqK1fIfy8doog" line="2"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_A9Ajgd56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_A9Ajgt56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_A9Ajg956EeqK1fIfy8doog" name="nombre_evento" content="nombre_evento" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_A9AjhN56EeqK1fIfy8doog" name="nombre_evento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_A9Ajhd56EeqK1fIfy8doog" content=""/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_A9Ajht56EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_A9Ajh956EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_A9AjiN56EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_A9Ajid56EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_A9Ajit56EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_A9Aji956EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_A9AjjN56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_A9Ajjd56EeqK1fIfy8doog" name="Nombre de evento" content="Nombre de evento" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_A9Ajjt56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_A9Ajj956EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_A9AjkN56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_A9Ajkd56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_A9Ajkt56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_A9Ajk956EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_A9AjlN56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_A9BKYN56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_A9BKYd56EeqK1fIfy8doog" name="Enviar1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_A9BKYt56EeqK1fIfy8doog" line="3"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_A9BKY956EeqK1fIfy8doog" name="Enviar" content="Enviar" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_A9BKZN56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_A9BKZd56EeqK1fIfy8doog" name="Eventos" content="Eventos" returnTypeFixed="true"/>
          </form>
          <transientData xmi:type="process:Data" xmi:id="_e-f2cN55EeqK1fIfy8doog" name="nombre_evento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_e-f2cd55EeqK1fIfy8doog" content=""/>
          </transientData>
          <transientData xmi:type="process:Data" xmi:id="_f4gnoN55EeqK1fIfy8doog" name="descripcion" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_f4hOsN55EeqK1fIfy8doog" content=""/>
          </transientData>
          <transientData xmi:type="process:Data" xmi:id="_hYjeEN55EeqK1fIfy8doog" name="fecha" dataType="_DcZ0Y95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_hYjeEd55EeqK1fIfy8doog" content="" returnType="java.util.Date"/>
          </transientData>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_Y9koFt50EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_Y9koF950EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_GgAn8N5xEeqK1fIfy8doog" name="Preincubación">
        <elements xmi:type="process:ANDGateway" xmi:id="_riMrwN5yEeqK1fIfy8doog" name="¿el proyecto tiene potencial?" outgoing="_tFylcN5yEeqK1fIfy8doog _0mJYgN5yEeqK1fIfy8doog" incoming="_riSLUN5yEeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_riNS095yEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_riNS0d5yEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_riNS0N5yEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_riNS0t5yEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_F8mG8N5zEeqK1fIfy8doog" name="¿financiado?" outgoing="_T1KZQN5zEeqK1fIfy8doog _D90QoN50EeqK1fIfy8doog" incoming="_F8qYYN5zEeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_F8muA95zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F8muAd5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F8muAN5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F8muAt5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Z6yeQN50EeqK1fIfy8doog" name="Identificación de potencial crecimiento" outgoing="_riSLUN5yEeqK1fIfy8doog" incoming="_6r6SUN5xEeqK1fIfy8doog" actor="_3RTFQN50EeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_6rxIZN5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6rxIYt5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6rxIYd5xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6rxIY95xEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_6rxIZ95xEeqK1fIfy8doog">
            <cardinality xmi:type="expression:Expression" xmi:id="_6rxIaN5xEeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_6rxIad5xEeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6rxIZd5xEeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6rxIZt5xEeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_L8DDwN56EeqK1fIfy8doog" name="IdentificaciónDePotencialCrecimiento" nLine="3">
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_L8DDwd56EeqK1fIfy8doog" name="tiene_potencial1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_L8DDwt56EeqK1fIfy8doog"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_L8DDw956EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_L8DDxN56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_L8DDxd56EeqK1fIfy8doog" name="tiene_potencial" content="tiene_potencial" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_L8DDxt56EeqK1fIfy8doog" name="tiene_potencial" dataType="_DcZ0Yt5uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_L8DDx956EeqK1fIfy8doog" content="" returnType="java.lang.Boolean"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_L8DDyN56EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_L8DDyd56EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_L8DDyt56EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_L8DDy956EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_L8DDzN56EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_L8DDzd56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_L8DDzt56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_L8DDz956EeqK1fIfy8doog" name="Tiene potencial" content="Tiene potencial" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_L8DD0N56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_L8DD0d56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_L8DD0t56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_L8DD0956EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_L8DD1N56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_L8DD1d56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_L8DD1t56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_L8DD1956EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_L8DD2N56EeqK1fIfy8doog" name="Enviar1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_L8DD2d56EeqK1fIfy8doog" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_L8Dq0N56EeqK1fIfy8doog" name="Enviar" content="Enviar" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_L8Dq0d56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_L8Dq0t56EeqK1fIfy8doog" name="Identificación de potencial crecimiento" content="Identificación de potencial crecimiento" returnTypeFixed="true"/>
          </form>
          <transientData xmi:type="process:Data" xmi:id="_kJbDMN55EeqK1fIfy8doog" name="tiene_potencial" dataType="_DcZ0Yt5uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_kJbDMd55EeqK1fIfy8doog" content="" returnType="java.lang.Boolean"/>
          </transientData>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_Z6zFVt50EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_Z6zFV950EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ahB-4N50EeqK1fIfy8doog" name="Desarrollo del programa entrenamiento emprendedor" outgoing="_F8qYYN5zEeqK1fIfy8doog" incoming="_0mJYgN5yEeqK1fIfy8doog" actor="_3RTFQN50EeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_0mDR495yEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0mDR4d5yEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0mDR4N5yEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0mDR4t5yEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_0mDR5t5yEeqK1fIfy8doog">
            <cardinality xmi:type="expression:Expression" xmi:id="_0mDR595yEeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_0mDR6N5yEeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0mDR5N5yEeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0mDR5d5yEeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_PzeoUN56EeqK1fIfy8doog" name="DesarrolloDelProgramaEntrenamientoEmprendedor" nLine="3">
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_PzeoUd56EeqK1fIfy8doog" name="asistido_a_programa1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_PzeoUt56EeqK1fIfy8doog"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_PzeoU956EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_PzeoVN56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_PzeoVd56EeqK1fIfy8doog" name="asistido_a_programa" content="asistido_a_programa" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_PzeoVt56EeqK1fIfy8doog" name="asistido_a_programa" dataType="_DcZ0Yt5uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_PzeoV956EeqK1fIfy8doog" content="" returnType="java.lang.Boolean"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_PzeoWN56EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_PzeoWd56EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_PzeoWt56EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_PzeoW956EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_PzeoXN56EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_PzeoXd56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_PzeoXt56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_PzeoX956EeqK1fIfy8doog" name="Asistió a programa" content="Asistió a programa" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_PzeoYN56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_PzeoYd56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_PzeoYt56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_PzeoY956EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_PzeoZN56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_PzeoZd56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_PzeoZt56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_PzeoZ956EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_PzeoaN56EeqK1fIfy8doog" name="Enviar1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_Pzeoad56EeqK1fIfy8doog" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_Pzeoat56EeqK1fIfy8doog" name="Enviar" content="Enviar" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_Pzeoa956EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_PzeobN56EeqK1fIfy8doog" name="Desarrollo del programa entrenamiento emprendedor" content="Desarrollo del programa entrenamiento emprendedor" returnTypeFixed="true"/>
          </form>
          <transientData xmi:type="process:Data" xmi:id="_qrawkN55EeqK1fIfy8doog" name="asistido_a_programa" dataType="_DcZ0Yt5uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_qrawkd55EeqK1fIfy8doog" content="" returnType="java.lang.Boolean"/>
          </transientData>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_ahB-5950EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_ahB-6N50EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_IQMzMN5xEeqK1fIfy8doog" name="Incubación">
        <elements xmi:type="process:ANDGateway" xmi:id="_bSefYN5zEeqK1fIfy8doog" name="¿startup aceptada?" outgoing="_dV_2UN5zEeqK1fIfy8doog _jQHrYN5zEeqK1fIfy8doog" incoming="_bSiJwN5zEeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_bSfGcN5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bSefYt5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bSefYd5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bSefY95zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_upcUEN5zEeqK1fIfy8doog" name="Fin" incoming="_uqIQkN5zEeqK1fIfy8doog _1F1IsN5zEeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_upc7I95zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_upc7Id5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_upc7IN5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_upc7It5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_bYjcwN50EeqK1fIfy8doog" name="Gestión de selección de startups" outgoing="_bSiJwN5zEeqK1fIfy8doog" incoming="_T1KZQN5zEeqK1fIfy8doog _dV_2UN5zEeqK1fIfy8doog" actor="_3RTFQN50EeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_T1Fgw95zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_T1Fgwd5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_T1FgwN5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_T1Fgwt5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_T1Fgxt5zEeqK1fIfy8doog">
            <cardinality xmi:type="expression:Expression" xmi:id="_T1Fgx95zEeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_T1FgyN5zEeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_T1FgxN5zEeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_T1Fgxd5zEeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_TocHsN56EeqK1fIfy8doog" name="GestiónDeSelecciónDeStartups" nLine="3">
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_TocHsd56EeqK1fIfy8doog" name="seleccionado1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_TocHst56EeqK1fIfy8doog"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_TocHs956EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_TocHtN56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_TocHtd56EeqK1fIfy8doog" name="seleccionado" content="seleccionado" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_TocHtt56EeqK1fIfy8doog" name="seleccionado" dataType="_DcZ0Yt5uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_TocHt956EeqK1fIfy8doog" content="" returnType="java.lang.Boolean"/>
                </referencedElements>
              </inputExpression>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_TocHuN56EeqK1fIfy8doog" name="" content=""/>
              <action xmi:type="expression:Operation" xmi:id="_TocHud56EeqK1fIfy8doog">
                <leftOperand xmi:type="expression:Expression" xmi:id="_TocHut56EeqK1fIfy8doog"/>
                <operator xmi:type="expression:Operator" xmi:id="_TocHu956EeqK1fIfy8doog" type="ASSIGNMENT" expression="="/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_TocHvN56EeqK1fIfy8doog"/>
              </action>
              <tooltip xmi:type="expression:Expression" xmi:id="_TocHvd56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_TocHvt56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_TocHv956EeqK1fIfy8doog" name="Startup seleccionada" content="Startup seleccionada" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_TocHwN56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_TocHwd56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_TocHwt56EeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_TocHw956EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_TocHxN56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_TocHxd56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_TocHxt56EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_TocHx956EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_TocHyN56EeqK1fIfy8doog" name="Enviar1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_TocHyd56EeqK1fIfy8doog" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_TocHyt56EeqK1fIfy8doog" name="Enviar" content="Enviar" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_TocHy956EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_TocHzN56EeqK1fIfy8doog" name="Gestión de selección de startups" content="Gestión de selección de startups" returnTypeFixed="true"/>
          </form>
          <transientData xmi:type="process:Data" xmi:id="_t6vMQN55EeqK1fIfy8doog" name="seleccionado" dataType="_DcZ0Yt5uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
            <defaultValue xmi:type="expression:Expression" xmi:id="_t6vMQd55EeqK1fIfy8doog" content="" returnType="java.lang.Boolean"/>
          </transientData>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_bYkD1t50EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_bYkD1950EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_cB3fgN50EeqK1fIfy8doog" name="Desarrollo del programa de inserción al mercado" outgoing="_uqIQkN5zEeqK1fIfy8doog" incoming="_jQHrYN5zEeqK1fIfy8doog" actor="_3RTFQN50EeqK1fIfy8doog">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_jQDZ8d5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jQCy4t5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jQCy4d5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jQDZ8N5zEeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:type="process:MultiInstantiation" xmi:id="_jQDZ9N5zEeqK1fIfy8doog">
            <cardinality xmi:type="expression:Expression" xmi:id="_jQDZ9d5zEeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <completionCondition xmi:type="expression:Expression" xmi:id="_jQDZ9t5zEeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jQDZ8t5zEeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jQDZ895zEeqK1fIfy8doog" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_2uzp8N55EeqK1fIfy8doog" name="DesarrolloDelProgramaDeInserciónAlMercado" nColumn="2" nLine="3">
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_2uzp8d55EeqK1fIfy8doog" name="Enviar1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_2uzp8t55EeqK1fIfy8doog" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_2uzp8955EeqK1fIfy8doog" name="Aceptado" content="Aceptado" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_2uzp9N55EeqK1fIfy8doog" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_2uzp9d55EeqK1fIfy8doog" name="Desarrollo del programa de inserción al mercado" content="Desarrollo del programa de inserción al mercado" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_cB4Glt50EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_cB4Gl950EeqK1fIfy8doog" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_EA1XIN5uEeqbhffMpNXt5w" path="_Dpo_IN5uEeqbhffMpNXt5w/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_Dpvs4N5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_Dpvs395uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_EA1-MN5uEeqbhffMpNXt5w" path="_Dpo_IN5uEeqbhffMpNXt5w/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_EA1XId5uEeqbhffMpNXt5w" path="_Dpo_IN5uEeqbhffMpNXt5w/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_EA1-Md5uEeqbhffMpNXt5w" path="_Dpo_IN5uEeqbhffMpNXt5w/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_EA1XIt5uEeqbhffMpNXt5w" path="_Dpo_IN5uEeqbhffMpNXt5w/html/consultation.html"/>
      <transientData xmi:type="process:Data" xmi:id="_CaTvIN53EeqK1fIfy8doog" name="convocatoria" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
        <defaultValue xmi:type="expression:Expression" xmi:id="_CaTvId53EeqK1fIfy8doog" content=""/>
      </transientData>
      <transientData xmi:type="process:Data" xmi:id="_EkSTYN53EeqK1fIfy8doog" name="titulo_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
        <defaultValue xmi:type="expression:Expression" xmi:id="_EkSTYd53EeqK1fIfy8doog" content=""/>
      </transientData>
      <transientData xmi:type="process:Data" xmi:id="_G3basN53EeqK1fIfy8doog" name="ubicacion_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
        <defaultValue xmi:type="expression:Expression" xmi:id="_G3basd53EeqK1fIfy8doog" content=""/>
      </transientData>
      <transientData xmi:type="process:Data" xmi:id="_I7C4QN53EeqK1fIfy8doog" name="resumen_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
        <defaultValue xmi:type="expression:Expression" xmi:id="_I7C4Qd53EeqK1fIfy8doog" content=""/>
      </transientData>
      <transientData xmi:type="process:Data" xmi:id="_KyFSYN53EeqK1fIfy8doog" name="descripcion_de_emprendimiento" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
        <defaultValue xmi:type="expression:Expression" xmi:id="_KyFSYd53EeqK1fIfy8doog" content=""/>
      </transientData>
      <transientData xmi:type="process:Data" xmi:id="_Mnf74N53EeqK1fIfy8doog" name="necesidad_de_mercado" dataType="_DcZ0Z95uEeqbhffMpNXt5w" datasourceId="PAGEFLOW">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Mnf74d53EeqK1fIfy8doog" content=""/>
      </transientData>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_Dpvs4t5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_Dpvs4d5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_Dpvs495uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_Dpvs3t5uEeqbhffMpNXt5w" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D25_EN5uEeqbhffMpNXt5w" source="_D1Y8IN5uEeqbhffMpNXt5w" target="_DxHgIN5uEeqbhffMpNXt5w" pathToken="_Dpo_IN5uEeqbhffMpNXt5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D26mIN5uEeqbhffMpNXt5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_D26mId5uEeqbhffMpNXt5w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aj-skN5xEeqK1fIfy8doog" source="_DxHgIN5uEeqbhffMpNXt5w" target="_N_Sc8N5xEeqK1fIfy8doog" pathToken="_Dpo_IN5uEeqbhffMpNXt5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aj_ToN5xEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_aj_Tod5xEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hHTPoN5xEeqK1fIfy8doog" name="si" source="_N_Sc8N5xEeqK1fIfy8doog" target="_hHNwEN5xEeqK1fIfy8doog" pathToken="_N_Sc8N5xEeqK1fIfy8doog">
        <expression xmi:type="expression:Expression" xmi:id="_8OfJQN56EeqK1fIfy8doog" content=""/>
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hHTPod5xEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_hHTPot5xEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_krUI8N5xEeqK1fIfy8doog" name="no" source="_hHNwEN5xEeqK1fIfy8doog" target="_DxHgIN5uEeqbhffMpNXt5w" pathToken="_hHNwEN5xEeqK1fIfy8doog">
        <expression xmi:type="expression:Expression" xmi:id="_H3oZ0N5_EeqK1fIfy8doog" content=""/>
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_krUwAN5xEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_krUwAd5xEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sFI2MN5xEeqK1fIfy8doog" name="si" source="_hHNwEN5xEeqK1fIfy8doog" target="_Y9kBAN50EeqK1fIfy8doog" pathToken="_hHNwEN5xEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sFI2Md5xEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_sFI2Mt5xEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_u8-mAN5xEeqK1fIfy8doog" source="_Y9kBAN50EeqK1fIfy8doog" target="_u85GcN5xEeqK1fIfy8doog" pathToken="_N_Sc8N5xEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_u8-mAd5xEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_u8-mAt5xEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xMcHMN5xEeqK1fIfy8doog" name="no" source="_u85GcN5xEeqK1fIfy8doog" target="_Y9kBAN50EeqK1fIfy8doog" pathToken="_u85GcN5xEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xMcuQN5xEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_xMcuQd5xEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6r6SUN5xEeqK1fIfy8doog" name="si" source="_u85GcN5xEeqK1fIfy8doog" target="_Z6yeQN50EeqK1fIfy8doog" pathToken="_u85GcN5xEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6r6SUd5xEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_6r6SUt5xEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_riSLUN5yEeqK1fIfy8doog" source="_Z6yeQN50EeqK1fIfy8doog" target="_riMrwN5yEeqK1fIfy8doog" pathToken="_u85GcN5xEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_riSLUd5yEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_riSLUt5yEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tFylcN5yEeqK1fIfy8doog" name="no" source="_riMrwN5yEeqK1fIfy8doog" target="_Y9kBAN50EeqK1fIfy8doog" pathToken="_riMrwN5yEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tFylcd5yEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_tFylct5yEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0mJYgN5yEeqK1fIfy8doog" name="si" source="_riMrwN5yEeqK1fIfy8doog" target="_ahB-4N50EeqK1fIfy8doog" pathToken="_riMrwN5yEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0mJ_kN5yEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_0mJ_kd5yEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_F8qYYN5zEeqK1fIfy8doog" source="_ahB-4N50EeqK1fIfy8doog" target="_F8mG8N5zEeqK1fIfy8doog" pathToken="_riMrwN5yEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_F8qYYd5zEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_F8qYYt5zEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_T1KZQN5zEeqK1fIfy8doog" name="si" source="_F8mG8N5zEeqK1fIfy8doog" target="_bYjcwN50EeqK1fIfy8doog" pathToken="_F8mG8N5zEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_T1KZQd5zEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_T1KZQt5zEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bSiJwN5zEeqK1fIfy8doog" source="_bYjcwN50EeqK1fIfy8doog" target="_bSefYN5zEeqK1fIfy8doog" pathToken="_riMrwN5yEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bSiJwd5zEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_bSiJwt5zEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dV_2UN5zEeqK1fIfy8doog" name="no" source="_bSefYN5zEeqK1fIfy8doog" target="_bYjcwN50EeqK1fIfy8doog" pathToken="_bSefYN5zEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dV_2Ud5zEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_dV_2Ut5zEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jQHrYN5zEeqK1fIfy8doog" name="si" source="_bSefYN5zEeqK1fIfy8doog" target="_cB3fgN50EeqK1fIfy8doog" pathToken="_bSefYN5zEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jQHrYd5zEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_jQHrYt5zEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uqIQkN5zEeqK1fIfy8doog" source="_cB3fgN50EeqK1fIfy8doog" target="_upcUEN5zEeqK1fIfy8doog" pathToken="_bSefYN5zEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uqI3oN5zEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_uqI3od5zEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1F1IsN5zEeqK1fIfy8doog" name="no" source="_N_Sc8N5xEeqK1fIfy8doog" target="_upcUEN5zEeqK1fIfy8doog" pathToken="_N_Sc8N5xEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1F1Isd5zEeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_1F1Ist5zEeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D90QoN50EeqK1fIfy8doog" name="no" source="_F8mG8N5zEeqK1fIfy8doog" target="_Y9kBAN50EeqK1fIfy8doog" pathToken="_F8mG8N5zEeqK1fIfy8doog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D903sN50EeqK1fIfy8doog"/>
        <condition xmi:type="expression:Expression" xmi:id="_D903sd50EeqK1fIfy8doog" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_DwM6IN5uEeqbhffMpNXt5w" documentation="Este es un ejemplo del actor que está asignado a ningún usuario ACME" name="Employee actor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_1MUVwN50EeqK1fIfy8doog" name="Emprendedor"/>
      <actors xmi:type="process:Actor" xmi:id="_3RTFQN50EeqK1fIfy8doog" name="Encargado(os) Jaku"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_DpvFwN5uEeqbhffMpNXt5w">
        <name xmi:type="expression:Expression" xmi:id="_Dpvs0N5uEeqbhffMpNXt5w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Dpvs0d5uEeqbhffMpNXt5w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Dpvs0t5uEeqbhffMpNXt5w">
        <name xmi:type="expression:Expression" xmi:id="_Dpvs095uEeqbhffMpNXt5w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Dpvs1N5uEeqbhffMpNXt5w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Dpvs1d5uEeqbhffMpNXt5w">
        <name xmi:type="expression:Expression" xmi:id="_Dpvs1t5uEeqbhffMpNXt5w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Dpvs195uEeqbhffMpNXt5w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Dpvs2N5uEeqbhffMpNXt5w">
        <name xmi:type="expression:Expression" xmi:id="_Dpvs2d5uEeqbhffMpNXt5w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Dpvs2t5uEeqbhffMpNXt5w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Dpvs295uEeqbhffMpNXt5w">
        <name xmi:type="expression:Expression" xmi:id="_Dpvs3N5uEeqbhffMpNXt5w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Dpvs3d5uEeqbhffMpNXt5w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_DcZ0Yt5uEeqbhffMpNXt5w" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_DcZ0Y95uEeqbhffMpNXt5w" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_DcZ0ZN5uEeqbhffMpNXt5w" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_DcZ0Zd5uEeqbhffMpNXt5w" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_DcZ0Zt5uEeqbhffMpNXt5w" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_DcZ0Z95uEeqbhffMpNXt5w" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_DcZ0aN5uEeqbhffMpNXt5w" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_DcZ0ad5uEeqbhffMpNXt5w" name="XML"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_DcabcN5uEeqbhffMpNXt5w" type="Process" element="_DcZ0Yd5uEeqbhffMpNXt5w" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_Dq-b4N5uEeqbhffMpNXt5w" type="2007" element="_Dpo_IN5uEeqbhffMpNXt5w">
      <children xmi:type="notation:DecorationNode" xmi:id="_DrBfMN5uEeqbhffMpNXt5w" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_DrBfMd5uEeqbhffMpNXt5w" type="7001">
        <children xmi:type="notation:Node" xmi:id="_DwWEEN5uEeqbhffMpNXt5w" type="3007" element="_DwTn0N5uEeqbhffMpNXt5w">
          <children xmi:type="notation:DecorationNode" xmi:id="_DwWEFd5uEeqbhffMpNXt5w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_DwWEFt5uEeqbhffMpNXt5w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_DxON0N5uEeqbhffMpNXt5w" type="3005" element="_DxHgIN5uEeqbhffMpNXt5w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_DxO04N5uEeqbhffMpNXt5w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DxON0d5uEeqbhffMpNXt5w" x="160" y="42" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D1itIN5uEeqbhffMpNXt5w" type="3002" element="_D1Y8IN5uEeqbhffMpNXt5w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D1itIt5uEeqbhffMpNXt5w" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D1itI95uEeqbhffMpNXt5w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D1itId5uEeqbhffMpNXt5w" x="60" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_N_USIN5xEeqK1fIfy8doog" type="3009" element="_N_Sc8N5xEeqK1fIfy8doog" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_N_USIt5xEeqK1fIfy8doog" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_N_USI95xEeqK1fIfy8doog" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_N_USId5xEeqK1fIfy8doog" x="231" y="162"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_DwWEEd5uEeqbhffMpNXt5w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_DwWEEt5uEeqbhffMpNXt5w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_DwWEE95uEeqbhffMpNXt5w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_DwWEF95uEeqbhffMpNXt5w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DwWEFN5uEeqbhffMpNXt5w" x="-40" y="-20"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_DenTgN5xEeqK1fIfy8doog" type="3007" element="_DeafMd5xEeqK1fIfy8doog">
          <children xmi:type="notation:DecorationNode" xmi:id="_DeohoN5xEeqK1fIfy8doog" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Deohod5xEeqK1fIfy8doog" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_hHO-MN5xEeqK1fIfy8doog" type="3009" element="_hHNwEN5xEeqK1fIfy8doog" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_hHO-Mt5xEeqK1fIfy8doog" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hHPlQN5xEeqK1fIfy8doog" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hHO-Md5xEeqK1fIfy8doog" x="111" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_u86UkN5xEeqK1fIfy8doog" type="3009" element="_u85GcN5xEeqK1fIfy8doog" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_u86Ukt5xEeqK1fIfy8doog" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_u867oN5xEeqK1fIfy8doog" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_u86Ukd5xEeqK1fIfy8doog" x="519" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Y9koG950EeqK1fIfy8doog" type="3005" element="_Y9kBAN50EeqK1fIfy8doog" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Y9lPId50EeqK1fIfy8doog" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Y9lPIN50EeqK1fIfy8doog" x="273" y="75" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_DenTgd5xEeqK1fIfy8doog"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_DenTgt5xEeqK1fIfy8doog" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_DenTg95xEeqK1fIfy8doog"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Deohot5xEeqK1fIfy8doog"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DenThN5xEeqK1fIfy8doog" x="113" y="184"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_GgBPAN5xEeqK1fIfy8doog" type="3007" element="_GgAn8N5xEeqK1fIfy8doog">
          <children xmi:type="notation:DecorationNode" xmi:id="_GgB2EN5xEeqK1fIfy8doog" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_GgB2Ed5xEeqK1fIfy8doog" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_riN54N5yEeqK1fIfy8doog" type="3009" element="_riMrwN5yEeqK1fIfy8doog" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_riN54t5yEeqK1fIfy8doog" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_riN5495yEeqK1fIfy8doog" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_riN54d5yEeqK1fIfy8doog" x="319" y="46"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F8nVEN5zEeqK1fIfy8doog" type="3009" element="_F8mG8N5zEeqK1fIfy8doog" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_F8nVEt5zEeqK1fIfy8doog" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_F8nVE95zEeqK1fIfy8doog" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F8nVEd5zEeqK1fIfy8doog" x="764" y="46"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Z6zFW950EeqK1fIfy8doog" type="3005" element="_Z6yeQN50EeqK1fIfy8doog" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Z6zsYN50EeqK1fIfy8doog" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Z6zFXN50EeqK1fIfy8doog" x="83" y="46" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ahB-7N50EeqK1fIfy8doog" type="3005" element="_ahB-4N50EeqK1fIfy8doog" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ahCl8N50EeqK1fIfy8doog" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ahB-7d50EeqK1fIfy8doog" x="452" y="22" width="202" height="100"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_GgBPAd5xEeqK1fIfy8doog"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_GgBPAt5xEeqK1fIfy8doog" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_GgBPA95xEeqK1fIfy8doog"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_GgB2Et5xEeqK1fIfy8doog"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GgBPBN5xEeqK1fIfy8doog" x="50" y="500" width="1653" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_IQNaQN5xEeqK1fIfy8doog" type="3007" element="_IQMzMN5xEeqK1fIfy8doog">
          <children xmi:type="notation:DecorationNode" xmi:id="_IQOBUN5xEeqK1fIfy8doog" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_IQOBUd5xEeqK1fIfy8doog" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_bSfGcd5zEeqK1fIfy8doog" type="3009" element="_bSefYN5zEeqK1fIfy8doog" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_bSfGc95zEeqK1fIfy8doog" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bSfGdN5zEeqK1fIfy8doog" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bSfGct5zEeqK1fIfy8doog" x="361" y="67"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_upeJQN5zEeqK1fIfy8doog" type="3003" element="_upcUEN5zEeqK1fIfy8doog" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_upeJQt5zEeqK1fIfy8doog" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_upeJQ95zEeqK1fIfy8doog" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_upeJQd5zEeqK1fIfy8doog" x="860" y="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bYkq4950EeqK1fIfy8doog" type="3005" element="_bYjcwN50EeqK1fIfy8doog" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bYkq5d50EeqK1fIfy8doog" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bYkq5N50EeqK1fIfy8doog" x="108" y="60" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_cB4toN50EeqK1fIfy8doog" type="3005" element="_cB3fgN50EeqK1fIfy8doog" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_cB4tot50EeqK1fIfy8doog" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cB4tod50EeqK1fIfy8doog" x="548" y="41" width="190" height="95"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_IQNaQd5xEeqK1fIfy8doog"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_IQNaQt5xEeqK1fIfy8doog" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_IQNaQ95xEeqK1fIfy8doog"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_IQOBUt5xEeqK1fIfy8doog"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IQNaRN5xEeqK1fIfy8doog" x="50" y="750" width="1653" height="220"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Dq-b4d5uEeqbhffMpNXt5w"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Dq-b4t5uEeqbhffMpNXt5w" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Dq-b495uEeqbhffMpNXt5w"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_DrCGQN5uEeqbhffMpNXt5w"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Dq-b5N5uEeqbhffMpNXt5w"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Dcabcd5uEeqbhffMpNXt5w"/>
    <edges xmi:type="notation:Connector" xmi:id="_D3DwEN5uEeqbhffMpNXt5w" type="4001" element="_D25_EN5uEeqbhffMpNXt5w" source="_D1itIN5uEeqbhffMpNXt5w" target="_DxON0N5uEeqbhffMpNXt5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_D3E-MN5uEeqbhffMpNXt5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D3E-Md5uEeqbhffMpNXt5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D3DwEd5uEeqbhffMpNXt5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D3DwEt5uEeqbhffMpNXt5w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_akOkMN5xEeqK1fIfy8doog" type="4001" element="_aj-skN5xEeqK1fIfy8doog" source="_DxON0N5uEeqbhffMpNXt5w" target="_N_USIN5xEeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_akPLQN5xEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_akPLQd5xEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_akOkMd5xEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_akOkMt5xEeqK1fIfy8doog" points="[-68, 51, 3, -36]$[-68, 83, 3, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_akXHEN5xEeqK1fIfy8doog" id="(1.0,0.3625)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_akXHEd5xEeqK1fIfy8doog" id="(0.4186046511627907,0.09302325581395349)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hHT2sN5xEeqK1fIfy8doog" type="4001" element="_hHTPoN5xEeqK1fIfy8doog" source="_N_USIN5xEeqK1fIfy8doog" target="_hHO-MN5xEeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hHUdwN5xEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hHUdwd5xEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hHT2sd5xEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hHT2st5xEeqK1fIfy8doog" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_krV-IN5xEeqK1fIfy8doog" type="4001" element="_krUI8N5xEeqK1fIfy8doog" source="_hHO-MN5xEeqK1fIfy8doog" target="_DxON0N5uEeqbhffMpNXt5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_krV-I95xEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_krV-JN5xEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_krV-Id5xEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_krV-It5xEeqK1fIfy8doog" points="[-43, -7, -51, 240]$[-43, -146, -51, 101]$[29, -146, 21, 101]$[29, -234, 21, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_krYaYN5xEeqK1fIfy8doog" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_krYaYd5xEeqK1fIfy8doog" id="(0.0125,0.8375)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sFJdQN5xEeqK1fIfy8doog" type="4001" element="_sFI2MN5xEeqK1fIfy8doog" source="_hHO-MN5xEeqK1fIfy8doog" target="_Y9koG950EeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sFJdQ95xEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sFJdRN5xEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sFJdQd5xEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sFJdQt5xEeqK1fIfy8doog" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_u8_NEN5xEeqK1fIfy8doog" type="4001" element="_u8-mAN5xEeqK1fIfy8doog" source="_Y9koG950EeqK1fIfy8doog" target="_u86UkN5xEeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_u8_0IN5xEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_u8_0Id5xEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_u8_NEd5xEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_u8_NEt5xEeqK1fIfy8doog" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xMdVUN5xEeqK1fIfy8doog" type="4001" element="_xMcHMN5xEeqK1fIfy8doog" source="_u86UkN5xEeqK1fIfy8doog" target="_Y9koG950EeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xMdVU95xEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xMdVVN5xEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xMdVUd5xEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xMdVUt5xEeqK1fIfy8doog" points="[-22, -29, 215, -9]$[-22, -51, 215, -31]$[-230, -51, 7, -31]$[-230, -32, 7, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xMfKgN5xEeqK1fIfy8doog" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xMfKgd5xEeqK1fIfy8doog" id="(0.52,0.24)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6r6SU95xEeqK1fIfy8doog" type="4001" element="_6r6SUN5xEeqK1fIfy8doog" source="_u86UkN5xEeqK1fIfy8doog" target="_Z6zFW950EeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6r6SVt5xEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6r6SV95xEeqK1fIfy8doog" x="74" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6r6SVN5xEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6r6SVd5xEeqK1fIfy8doog" points="[8, 14, 390, -220]$[8, 77, 390, -157]$[-376, 77, 6, -157]$[-376, 197, 6, -37]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_riSLU95yEeqK1fIfy8doog" type="4001" element="_riSLUN5yEeqK1fIfy8doog" source="_Z6zFW950EeqK1fIfy8doog" target="_riN54N5yEeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_riSyYt5yEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_riSyY95yEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_riSyYN5yEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_riSyYd5yEeqK1fIfy8doog" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tFzMgN5yEeqK1fIfy8doog" type="4001" element="_tFylcN5yEeqK1fIfy8doog" source="_riN54N5yEeqK1fIfy8doog" target="_Y9koG950EeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tFzzkN5yEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tFzzkd5yEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tFzMgd5yEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tFzMgt5yEeqK1fIfy8doog" points="[-22, -30, 24, 193]$[-22, -217, 24, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tF1owN5yEeqK1fIfy8doog" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tF1owd5yEeqK1fIfy8doog" id="(0.43,0.88)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0mKmoN5yEeqK1fIfy8doog" type="4001" element="_0mJYgN5yEeqK1fIfy8doog" source="_riN54N5yEeqK1fIfy8doog" target="_ahB-7N50EeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0mKmo95yEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0mKmpN5yEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0mKmod5yEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0mKmot5yEeqK1fIfy8doog" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_F8q_cN5zEeqK1fIfy8doog" type="4001" element="_F8qYYN5zEeqK1fIfy8doog" source="_ahB-7N50EeqK1fIfy8doog" target="_F8nVEN5zEeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_F8q_c95zEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_F8q_dN5zEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_F8q_cd5zEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_F8q_ct5zEeqK1fIfy8doog" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_T1LnYN5zEeqK1fIfy8doog" type="4001" element="_T1KZQN5zEeqK1fIfy8doog" source="_F8nVEN5zEeqK1fIfy8doog" target="_bYkq4950EeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_T1LnY95zEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_T1LnZN5zEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_T1LnYd5zEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_T1LnYt5zEeqK1fIfy8doog" points="[8, 14, 610, -242]$[8, 123, 610, -133]$[-597, 123, 5, -133]$[-597, 219, 5, -37]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bSiw0N5zEeqK1fIfy8doog" type="4001" element="_bSiJwN5zEeqK1fIfy8doog" source="_bYkq4950EeqK1fIfy8doog" target="_bSfGcd5zEeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bSiw095zEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bSiw1N5zEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bSiw0d5zEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bSiw0t5zEeqK1fIfy8doog" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dWAdYN5zEeqK1fIfy8doog" type="4001" element="_dV_2UN5zEeqK1fIfy8doog" source="_bSfGcd5zEeqK1fIfy8doog" target="_bYkq4950EeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dWBEcN5zEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dWBEcd5zEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dWAdYd5zEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dWAdYt5zEeqK1fIfy8doog" points="[-22, -27, 172, 6]$[-22, -67, 172, -34]$[-216, -67, -22, -34]$[-216, -43, -22, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dWCSkN5zEeqK1fIfy8doog" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dWCSkd5zEeqK1fIfy8doog" id="(0.6466666666666666,0.13333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jQIScN5zEeqK1fIfy8doog" type="4001" element="_jQHrYN5zEeqK1fIfy8doog" source="_bSfGcd5zEeqK1fIfy8doog" target="_cB4toN50EeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jQI5gt5zEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jQI5g95zEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jQI5gN5zEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jQI5gd5zEeqK1fIfy8doog" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uqJesN5zEeqK1fIfy8doog" type="4001" element="_uqIQkN5zEeqK1fIfy8doog" source="_cB4toN50EeqK1fIfy8doog" target="_upeJQN5zEeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uqKFwN5zEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uqKFwd5zEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uqJesd5zEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uqJest5zEeqK1fIfy8doog" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1F1vwN5zEeqK1fIfy8doog" type="4001" element="_1F1IsN5zEeqK1fIfy8doog" source="_N_USIN5xEeqK1fIfy8doog" target="_upeJQN5zEeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1F2W0N5zEeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1F2W0d5zEeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1F1vwd5zEeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1F1vwt5zEeqK1fIfy8doog" points="[-3, -4, -599, -646]$[592, 636, -4, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1F294N5zEeqK1fIfy8doog" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1F294d5zEeqK1fIfy8doog" id="(0.3333333333333333,0.23333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D903st50EeqK1fIfy8doog" type="4001" element="_D90QoN50EeqK1fIfy8doog" source="_F8nVEN5zEeqK1fIfy8doog" target="_Y9koG950EeqK1fIfy8doog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_D91ewN50EeqK1fIfy8doog" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D91ewd50EeqK1fIfy8doog" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D903s950EeqK1fIfy8doog" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D903tN50EeqK1fIfy8doog" points="[-22, -28, 440, 181]$[-22, -118, 440, 91]$[-446, -118, 16, 91]$[-446, -199, 16, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_D92F0N50EeqK1fIfy8doog" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_D92s4N50EeqK1fIfy8doog" id="(0.72,0.8)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_h8NaMN54EeqK1fIfy8doog" type="Form" element="_h8H6oN54EeqK1fIfy8doog" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_h8NaMd54EeqK1fIfy8doog"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_2u5JgN55EeqK1fIfy8doog" type="Form" element="_2uzp8N55EeqK1fIfy8doog" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_2u5Jgd55EeqK1fIfy8doog"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_A9HRAN56EeqK1fIfy8doog" type="Form" element="_A9AjUN56EeqK1fIfy8doog" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_A9HRAd56EeqK1fIfy8doog"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_L8JKYN56EeqK1fIfy8doog" type="Form" element="_L8DDwN56EeqK1fIfy8doog" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_L8JKYd56EeqK1fIfy8doog"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_PznLMN56EeqK1fIfy8doog" type="Form" element="_PzeoUN56EeqK1fIfy8doog" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_PznLMd56EeqK1fIfy8doog"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_TokDgN56EeqK1fIfy8doog" type="Form" element="_TocHsN56EeqK1fIfy8doog" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_TokDgd56EeqK1fIfy8doog"/>
  </notation:Diagram>
</xmi:XMI>
